import assert from "node:assert/strict";
import fs from "node:fs";

const read = path => fs.readFileSync(new URL("../" + path, import.meta.url), "utf8");
const bookingBar = read("public_html/BookingBar.dc.html");
const nav = read("public_html/SiteNav.dc.html");
const routes = read("dev-server.py");
const proxy = read("public_html/api/gp/index.php");
const footer = read("public_html/SiteFooter.dc.html");
const terms = read("public_html/Terms.dc.html");
const bookingConfig = read("public_html/booking-config.js");
const home = read("public_html/Kosipark.dc.html");
const accommodation = read("public_html/Accommodation.dc.html");
const room = read("public_html/Room.dc.html");
const contact = read("public_html/Contact.dc.html");
const guestpoint = read("public_html/guestpoint.js");
const calendar = read("public_html/Calendar.dc.html");

assert.match(bookingBar, /startDate/);
assert.match(bookingBar, /numAdults/);
assert.match(bookingBar, /numChildren/);
assert.match(bookingBar, /numNights/);
assert.doesNotMatch(nav, /data-cart=/);
assert.match(nav, /label: "Availability"/);
assert.doesNotMatch(routes, /Checkout\.dc\.html/);
assert.doesNotMatch(routes, /Manage\.dc\.html/);
assert.doesNotMatch(proxy, /['"]reservations/);
assert.doesNotMatch(proxy, /portal\/update/);
assert.doesNotMatch(footer, /href="\/manage"/);
assert.doesNotMatch(terms, /href="\/manage"/);
assert.match(bookingConfig, /10092601\.bookus\.dev\//);
assert.match(bookingConfig, /bookingEnvironment:\s*"development"/);
assert.match(bookingConfig, /testCategoryLimit:\s*1/);
assert.doesNotMatch(bookingConfig, /coachmans-eden/);
assert.match(home, /kosipark-favicon-skier\.svg\?v=20260910/);
assert.match(home, /src="\/booking-config\.js"/);
assert.match(accommodation, /src="\/booking-config\.js"/);
assert.match(room, /src="\/booking-config\.js"/);
assert.match(contact, /\/assets\/park-map-2026\.jpg/);
assert.doesNotMatch(contact, /park-map-2026\.(pdf|preview\.jpg)/);
assert.match(contact, /download="Kosciuszko-Tourist-Park-Map-2026\.jpg"/);
assert.match(contact, /data-park-map-open/);
assert.doesNotMatch(contact, /target="_blank"[^>]+park-map-2026/);
assert.match(contact, /\.park-map-toggle:checked ~ \.park-map-dialog/);
assert.match(home, /perisher\.jpg/);
assert.match(home, /snowboarder-winter-v1\.jpg/);
assert.match(home, /bike-chairlift-v1\.jpg/);
assert.match(home, /campfire-evening-v1\.jpg/);
assert.match(home, /two-bedroom-chalet\/exterior-snow\.jpg/);
assert.match(home, /bushwalking\.jpg/);
assert.match(home, /fly-fishing\.jpg/);
assert.match(home, /mountain-bike-sunrise-v1\.jpg/);
assert.match(home, /summit-walk\.jpg/);
assert.match(home, /prefers-reduced-motion/);
assert.match(routes, /GP_API_KEY/);
assert.match(routes, /GP_PROPERTY_ID/);
assert.match(routes, /urllib\.request\.urlopen/);
assert.match(routes, /GP_HAR_FILE/);
assert.match(routes, /guestpoint-har-snapshot/);
assert.doesNotMatch(guestpoint, /h === "localhost"/);
assert.match(calendar, /Live GuestPoint availability/);
assert.match(calendar, /GuestPoint HAR test data/);
assert.match(calendar, /Checkout OK/);
assert.match(calendar, /i < nightsIfChosen/);
assert.match(calendar, /nightInfo\.soldOut/);
assert.match(calendar, /flattenAvailability/);
assert.match(calendar, /types: s\.types\.map/);
assert.match(calendar, /quoteSelection/);
assert.match(calendar, /getExtras/);
assert.match(calendar, /Price for your group/);
assert.match(calendar, /Smart options/);
assert.match(calendar, /bookDisabled/);

console.log("Kosipark V2 booking-boundary checks passed.");
